drcclpvmpc_main:
  ros__parameters:
    dt_: 0.05
    horizon_: 6
    track_width_: 4.0
    use_drcc: true
    control_type: "pwm"  # 'pwm'|'vx'
    # Below are parameters for the specific vehicle model
    lf: 1.3
    lr: 1.6
    mass: 1696.0
    Iz: 4036.0
    g: 9.81
    wheel_base: 1.45
    # Below are parameters for the vehicle MF tire model
    Bf: 10.668
    Cf: 1.104
    Df: 9.996

    Br: 2.559
    Cr: 2.60
    Dr: 19.855

    Caf: 117.69
    Car: 132.12
    # Below are parameters for the drivetrain model
    Cm1: 381.568
    Cm2: 688.387
    Cr0: 180.07
    Cd: 19.64

    # Below are parameters for the control limits
    max_steer: 70  # [deg]
    min_steer: -70 # [deg]

    max_vy: 10.0     # [m/s]
    min_vy: -10.0    # [m/s]

    max_vx: 10.0    # [m/s]
    min_vx: 0.0     # [m/s]

    max_acc: 3.0     # [m/s^2]
    min_acc: -6.0    # [m/s^2]

    max_omega: 50  # [rad/s]
    min_omega: -50 # [rad/s]

    # Below are parameters for the global path service name
    service_name: "get_path_from_txt"
    goal_topic: "/goal_pose"

    # Below defines the safety distance to the obstacle: safe_multiplier * max_vx
    safe_multiplier: 8.0

