obstacle_spawner:
  ros__parameters:
    inflation_radius: 1.0   # meters
    carla_host: "127.0.0.1"
    carla_port: 2000
    publish_rate_hz: 10.0
    vehicles:
      car1:
        blueprint: "vehicle.audi.tt"
        x: -211.7088012695312
        y: -95.2505874633789
        z: 0.1
        yaw: 180.0
      car2:
        blueprint: "vehicle.audi.tt"
        x: -273.014831542969
        y: -40.430727005004883
        z: 0.1
        yaw: 90.0
      car3:
        blueprint: "vehicle.audi.tt"
        x: -273.014831542969
        y: 40.430727005004883
        z: 0.1
        yaw: 90.0
      car4:
        blueprint: "vehicle.audi.tt"
        x: -225.7088012695312
        y: 95.2505874633789
        z: 0.1
        yaw: 0.0
