carla_vehicle_spawner:
  ros__parameters:
    carla_host: "127.0.0.1"
    carla_port: 2000
    carla_timeout: 5.0

    carla_map: "Town10HD_Opt"
    vehicle_blueprint: "vehicle.lincoln.mkz"
    role_name: "ego"
    enable_autopilot: false

    spawn_mode: "index"     # or "pose"
    spawn_index: 6 # 4,6

    # If using spawn_mode == "pose"
    spawn_x: 0.0
    spawn_y: 0.0
    spawn_z: 0.5
    spawn_roll: 0.0
    spawn_pitch: 0.0
    spawn_yaw: 0.0

    # Spectator chase-cam
    spectator_offset_x: -10.0   # behind
    spectator_offset_y: 0.0
    spectator_offset_z: 3.0
    spectator_smooth_tau_pos: 0.15
    spectator_smooth_tau_yaw: 0.20
    spectator_follow_lag_sec: 0.10
    spectator_yaw_lookahead_sec: 0.15

carla_lidar_attacher:
  ros__parameters:
    host: "127.0.0.1"
    port: 2000
    timeout: 5.0

    # Pick your vehicle (matches your car spawner)
    vehicle_actor_id: 0
    vehicle_role_name: "ego"             # easiest if your car was spawned with role_name=ego
    vehicle_blueprint: "vehicle.*"
    vehicle_blueprint_index: 0

    # LiDAR mount (relative to base_link)
    lidar_frame_id: "lidar_link"
    lidar_mount_x: 0.0
    lidar_mount_y: 0.0
    lidar_mount_z: 2.4
    lidar_mount_roll: 0.0
    lidar_mount_pitch: 0.0
    lidar_mount_yaw: 0.0

    # LiDAR sensor parameters
    range: 200.0
    channels: 64
    upper_fov: 10.0
    lower_fov: -30.0
    points_per_second: 1200000
    rotation_frequency: 50.0
    noise_stddev: 0.0
    dropoff_general_rate: 0.0
    dropoff_intensity_limit: 1.0
    dropoff_zero_intensity: 0.0
    atmosphere_attenuation_rate: 0.004
    sensor_tick: 0.0

carla_camera_attacher:
  ros__parameters:
    host: "127.0.0.1"
    port: 2000
    timeout: 5.0

    # Vehicle selection (match your spawner)
    vehicle_actor_id: 0
    vehicle_role_name: "ego"
    vehicle_blueprint: "vehicle.*"
    vehicle_blueprint_index: 0

    # Camera mount
    camera_frame_id: "camera_link"
    mount_x: 1.5
    mount_y: 0.0
    mount_z: 2.0
    mount_roll: 0.0
    mount_pitch: 0.0
    mount_yaw: 0.0

    # Sensor params
    image_width: 1280
    image_height: 720
    fov: 90.0
    sensor_tick: 0.0
    ros_image_encoding: "bgr8"     # or "bgra8"

    # CameraInfo
    publish_camera_info: true
    camera_info_frame_id: "camera_link"
    camera_info_topic: "carla/camera_info"

carla_odom_publisher:
  ros__parameters:
    host: "127.0.0.1"
    port: 2000
    rate_hz: 20.0

    # selection precedence: actor_id > role_name > blueprint
    vehicle_actor_id: 0
    vehicle_role_name: "ego"                 # set to "ego" if you tag the vehicle
    vehicle_blueprint: "vehicle.lincoln.mkz"
    vehicle_blueprint_index: 0

carla_vehicle_controller:
  ros__parameters:
    host: "127.0.0.1"
    port: 2000

    # Vehicle selection precedence: actor_id > role_name > blueprint
    vehicle_actor_id: 0
    vehicle_role_name: "ego"
    vehicle_blueprint: "vehicle.lincoln.mkz"
    vehicle_blueprint_index: 0

    # Accel→throttle/brake mapping (used if control_cmd_mode == "steer_accel")
    accel_to_throttle_gain: 0.25
    accel_to_brake_gain: 0.30
    deadband_accel: 0.05

    # Steering normalization & slew limit
    steer_saturation: 1.0
    steer_rate_limit: 2.0
    max_steer_angle_rad: 1.222        # steer_rad / this → steer_norm in [-1,1]

    # How to interpret /control_cmd data=[steer_rad, second, brake]:
    #  - "steer_throttle": second = throttle in [0,1] (default)
    #  - "steer_accel":    second = accel in m/s^2 (mapped to throttle/brake)
    control_cmd_mode: "steer_throttle"

    # Vehicle resolution
    resolve_period_sec: 0.5
    log_every_n_resolves: 10

    # === NEW: velocity PID control ===
    velocity_cmd_topic: "/velocity_cmd"   # Float32MultiArray: [velocity_mps, steer_rad, brake_binary]

    speed_pid_kp: 0.8
    speed_pid_ki: 0.2
    speed_pid_kd: 0.05
    speed_pid_i_max: 0.5                  # integral clamp
    speed_pid_throttle_max: 1.0           # throttle clamp
    speed_pid_alpha: 0.2                  # EMA smoothing for measured speed
